import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "../../../../components/header";
import Footer from "../../../../components/footer";
import CatalogContent from "../../../../components/collections/CatalogContent";

const inter = Inter({ subsets: ["latin"] });

const Page = () => {
  return (
    <>
      <Head>
        <title>stay gold studios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Header />
        <CatalogContent />
        <Footer />
      </main>
    </>
  );
};

export default Page;
